name: Order-Convert
on:                       # 以后 GPT 或你自己都可以触发这个事件
  repository_dispatch:
    types: [convert-order]

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      # ① 拉取代码
      - uses: actions/checkout@v4

      # ② 装 Python 3.11
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      # ③ 安装依赖
      - run: pip install pandas openpyxl

      # ④ 下载客户文件（GPT 触发时会传进来）
      - name: Download GPS report
        run: curl -L "$FILE_URL" -o input.xlsx
        env: { FILE_URL: ${{ github.event.client_payload.file_url }} }

      # ⑤ 运行你的脚本
      - name: Run converter
        run: python convert.py input.xlsx erp.csv --type ${{ github.event.client_payload.doc_type || 'po' }}

      # ⑥ 把结果打包（供后面下载）
      - uses: actions/upload-artifact@v4
        with: { name: erp-result, path: input_*O.csv }
